name: 'Setup Environment & Firmware Cache'
description: 'Sets up Python, dependencies, and caching for firmware archives.'
inputs:
  fw-password:
    description: 'Password for FW archive extraction'
    required: true
  install-test-deps:
    description: 'Whether to install test dependencies'
    required: false
    default: 'false'
runs:
  using: "composite"
  steps:
    - name: Set up Python
      uses: actions/setup-python@v6
      with:
        python-version: '3.14'
        cache: 'pip'
        cache-dependency-path: bin/requirements.txt

    - name: Install dependencies
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install -r bin/requirements.txt py7zr requests
        if [ "${{ inputs.install-test-deps }}" = "true" ]; then
          pip install pytest pytest-cov pypdl
        fi

    - name: Cache FW archive
      id: cache-fw
      uses: actions/cache@v5
      with:
        path: |
          tests/data/extracted
          tests/data/url.txt
        key: fw-extracted-v1-${{ hashFiles('tests/scripts/cache_fw.py') }}
        restore-keys: |
          fw-extracted-v1-

    - name: Prefetch FW archive
      if: steps.cache-fw.outputs.cache-hit != 'true'
      shell: bash
      env:
        TEST_FW_PASSWORD: ${{ inputs.fw-password }}
        PYTHONUNBUFFERED: "1"
        PYTHONPATH: "bin"
      run: |
        python tests/scripts/cache_fw.py
